import pytest
from bs4 import BeautifulSoup

from app import app

@pytest.fixture
def client():
    app.config['TESTING'] = True
    with app.test_client() as client:
        yield client

def test_index(client):  
    response = client.get('/')
    assert response.status_code == 200

def test_greet(client):
    response = client.post('/greet', data={
        'name': 'Sandeep Kumar Jyothula',
        'age': '26',
        'hobby': 'coding',
        'color': '#000000',
        'mood': 'happy'
    })
    soup = BeautifulSoup(response.data, 'html.parser')
    page_text = soup.get_text()
    page_text = soup.get_text(strip=True)

    # Check the actual output generated by the app
    assert "GreetingHello, Sandeep Kumar Jyothula!You are 26 years old.Your favorite hobby is coding." in page_text
