import pytest
from bs4 import BeautifulSoup

from app import app

@pytest.fixture
def client():
    app.config['TESTING'] = True
    with app.test_client() as client:
        yield client

def test_index(client):  
    response = client.get('/')
    assert response.status_code == 200

def test_greet(client):
    response = client.post('/greet', data={
        'name': 'Alex',
        'age': '25',
        'hobby': 'coding',
        'color': '#000000',
        'mood': 'happy'
    })
    soup = BeautifulSoup(response.data, 'html.parser')
    page_text = soup.get_text()
    page_text = soup.get_text(strip=True)

    # Check the actual output generated by the app
    assert "GreetingYou're in the prime of your life!Enjoy your time coding-ing!Glad to hear you're in a good mood!" in page_text
