name: Deploy Python Application

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: app  # Checkout to a specific folder

      - name: Copy code to VM
        run: |
          sshpass -p ${{ secrets.DEPLOY_PASSWORD }} scp -r -o StrictHostKeyChecking=no ./app root@${{ secrets.DEPLOY_IP }}:/app

      - name: Install dependencies
        run: |
          sshpass -p ${{ secrets.DEPLOY_PASSWORD }} ssh -o StrictHostKeyChecking=no root@${{ secrets.DEPLOY_IP }} << 'EOF'
            ls /app
            cd /app  # Change this to your app directory
            python3 -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt
            # Kill existing Gunicorn processes
            pkill gunicorn || true  # Use || true to ignore errors if no process is found
            gunicorn app:app --bind 0.0.0.0:80 --daemon  # Change the port if needed
            echo "Application is deployed...!"
          EOF
