name: Deploy Flask Application

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: app  # Checkout the application code into the "app" directory

      # Step 2: Set up SSH Agent
      - name: Set up SSH Agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ vars.SSH_PRIVATE_KEY }}

      # Step 3: Clean up /app directory on VM1
      - name: Clean up /app directory on VM1
        run: |
          ssh -o StrictHostKeyChecking=no sandyvirat9@${{ vars.VM1_IP }} << 'EOF'
            sudo rm -rf /app/*
            sudo mkdir -p /app
            sudo chown -R sandyvirat9:sandyvirat9 /app
          EOF

      # Step 4: Copy application code to VM1
      - name: Copy application code to VM1
        run: |
          scp -o StrictHostKeyChecking=no -r ./app/. sandyvirat9@${{ vars.VM1_IP }}:/app

      # Step 5: Set up Python environment and start Gunicorn on VM1
      - name: Set up Python environment and start Gunicorn on VM1
        run: |
          ssh -o StrictHostKeyChecking=no sandyvirat9@${{ vars.VM1_IP }} << 'EOF'
            cd /app
            python3 -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt
            pkill gunicorn || true
            gunicorn app:app --bind 0.0.0.0:5000 --daemon
            echo "Application deployed and running on VM1!"
          EOF

      # Step 6: Clean up /app directory on VM2
      - name: Clean up /app directory on VM2
        run: |
          ssh -o StrictHostKeyChecking=no sandyvirat9@${{ vars.VM2_IP }} << 'EOF'
            sudo rm -rf /app/*
            sudo mkdir -p /app
            sudo chown -R sandyvirat9:sandyvirat9 /app
          EOF

      # Step 7: Copy application code to VM2
      - name: Copy application code to VM2
        run: |
          scp -o StrictHostKeyChecking=no -r ./app/. sandyvirat9@${{ vars.VM2_IP }}:/app

      # Step 8: Set up Python environment and start Gunicorn on VM2
      - name: Set up Python environment and start Gunicorn on VM2
        run: |
          ssh -o StrictHostKeyChecking=no sandyvirat9@${{ vars.VM2_IP }} << 'EOF'
            cd /app
            python3 -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt
            pkill gunicorn || true
            gunicorn app:app --bind 0.0.0.0:5000 --daemon
            echo "Application deployed and running on VM2!"
          EOF
