name: Deploy Flask Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: app

      - name: Set up SSH Agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ var.SSH_PRIVATE_KEY }}

      - name: Deploy to VM1
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_ed25519 sandyvirat9@${{ vars.VM1_IP }} << 'EOF'
            mkdir -p /app
            cd /app
            echo "Deployment successful on VM1"
          EOF

      - name: Deploy to VM2
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_ed25519 sandyvirat9@${{ vars.VM2_IP }} << 'EOF'
            mkdir -p /app
            cd /app
            echo "Deployment successful on VM2"
          EOF
