name: Deploy Python Application

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: app  # Checkout to a specific folder

      - name: Set up SSH Agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}

      - name: Prepare VM
        run: |
          ssh -o StrictHostKeyChecking=no sandyvirat9@${{ secrets.DEPLOY_IP }} << 'EOF'
            # Create /app directory with proper permissions
            sudo mkdir -p /app
            sudo chown -R sandyvirat9:sandyvirat9 /app
          EOF

      - name: Copy code to VM
        run: |
          scp -o StrictHostKeyChecking=no -r ./app sandyvirat9@${{ secrets.DEPLOY_IP }}:/app

      - name: Install dependencies and run Flask
        run: |
          ssh -o StrictHostKeyChecking=no sandyvirat9@${{ secrets.DEPLOY_IP }} << 'EOF'
            ls /app
            cd /app
            python3 -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt
            pkill gunicorn || true  # Use || true to ignore errors if no process is found
            gunicorn app:app --bind 0.0.0.0:5000 --daemon \
            --error-logfile /var/log/gunicorn.error.log \
            --access-logfile /var/log/gunicorn.access.log
            echo "Application is deployed...!"
          EOF
