name: Bootstrap VM

on:
  workflow_dispatch:
    inputs:
      ip_address:
        description: 'IP Address of the VM'
        required: true

jobs:
  bootstrap:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies for bootstrap
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass

      - name: Bootstrap VM
        run: |
          sshpass -p ${{ secrets.DEPLOY_PASSWORD }} ssh -o StrictHostKeyChecking=no root@${{ github.event.inputs.ip_address }} << 'EOF'
            mkdir -p /app  # Ensure the /app directory is created
            # Your bootstrap commands here
            sudo apt-get update
            sudo apt-get install -y python3-pip  # Ensure pip is installed
            sudo apt-get install -y python3 python3-venv
            # Any other setup commands you need
            echo "Bootstrapping is done...!"
          EOF
