name: Deploy Flask Application

on:
  push:
    branches:
      - master 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: app  # Checkout the application code

      - name: Set up SSH Agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ vars.SSH_PRIVATE_KEY }}  # Use private key from variables

      - name: Deploy to VM1
        run: |
          # Copy application code to the VM
          scp -o StrictHostKeyChecking=no -r ./app sandyvirat9@${{ vars.VM1_IP }}:/app
          
          # Connect to the VM and set up the Flask application
          ssh -o StrictHostKeyChecking=no sandyvirat9@${{ vars.VM1_IP }} << 'EOF'
            cd /app

            # Create a Python virtual environment and install dependencies
            python3 -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt

            # Stop any existing Gunicorn processes
            pkill gunicorn || true

            # Start the Flask application with Gunicorn
            gunicorn app:app --bind 0.0.0.0:5000 --daemon

            echo "Application deployed and running on VM1!"
          EOF

      - name: Deploy to VM2
        run: |
          # Copy application code to the VM
          scp -o StrictHostKeyChecking=no -r ./app sandyvirat9@${{ vars.VM2_IP }}:/app
          
          # Connect to the VM and set up the Flask application
          ssh -o StrictHostKeyChecking=no sandyvirat9@${{ vars.VM2_IP }} << 'EOF'
            cd /app

            # Create a Python virtual environment and install dependencies
            python3 -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt

            # Stop any existing Gunicorn processes
            pkill gunicorn || true

            # Start the Flask application with Gunicorn
            gunicorn app:app --bind 0.0.0.0:5000 --daemon

            echo "Application deployed and running on VM2!"
          EOF
