name: Deploy Flask Application

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout Code
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: app

      # Step 2: Set up SSH Agent
      - name: Set up SSH Agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ vars.SSH_PRIVATE_KEY }}

      # Step 3: Deploy to VM1
      - name: Ensure Required Packages on VM1
        run: |
          ssh -o StrictHostKeyChecking=no sandyvirat9@${{ vars.VM1_IP }} << 'EOF'
            sudo apt update
            sudo apt install -y python3-venv python3-pip
          EOF

      - name: Copy Application Code to VM1
        run: |
          scp -o StrictHostKeyChecking=no -r ./app sandyvirat9@${{ vars.VM1_IP }}:/app

      - name: Deploy Flask Application on VM1
        run: |
          ssh -o StrictHostKeyChecking=no sandyvirat9@${{ vars.VM1_IP }} << 'EOF'
            cd /app
            source venv/bin/activate
            pip install -r requirements.txt
            pkill gunicorn || true
            gunicorn app:app --bind 0.0.0.0:5000 --daemon
          EOF

      # Step 4: Deploy to VM2
      - name: Ensure Required Packages on VM2
        run: |
          ssh -o StrictHostKeyChecking=no sandyvirat9@${{ vars.VM2_IP }} << 'EOF'
            sudo apt update
            sudo apt install -y python3-venv python3-pip
          EOF

      - name: Copy Application Code to VM2
        run: |
          scp -o StrictHostKeyChecking=no -r ./app sandyvirat9@${{ vars.VM2_IP }}:/app

      - name: Deploy Flask Application on VM2
        run: |
          ssh -o StrictHostKeyChecking=no sandyvirat9@${{ vars.VM2_IP }} << 'EOF'
            cd /app
            source venv/bin/activate
            pip install -r requirements.txt
            pkill gunicorn || true
            gunicorn app:app --bind 0.0.0.0:5000 --daemon
          EOF
